### ISSUE TITLE
The way to create on-demand instance?

### ISSUE THREAD

**Issue by jinrangcui** [awslabs/ec2-spot-jenkins-plugin#14]
hi , I am an AWS user, may I ask for how to create an On-Demand kind of EC2 on Linux system, Can I use this template and just change "spot" to "on-demand"? thank you in advance.

**Comment by schmutze** [comment]
Hi @jinrangcui,

This particular repo is for hosting the Jenkins EC2 Spot Instances plugin.
For getting started with EC2 material, please see the following page:
https://aws.amazon.com/ec2/getting-started/

For example CloudFormation templates, please try this repo:
https://github.com/awslabs/aws-cloudformation-templates

thanks,
chad
