### ISSUE TITLE
Help !!!

### ISSUE THREAD

**Issue by harshana-rav** [awslabs/ec2-spot-jenkins-plugin#16]
I am trying to use the ec2 fleet plugin and I am having troubles get it going

So I have a AWS account and I created an AMI for jenkins to use
Added all the settings to "Manage Jenkins" > "Configure System"
I cant see Ec2 launching to start the Jenkins work 

I am using Jenkins ver. 2.87

**Comment by terma** [comment]
This repo was migrated under Jenkins organization (their requirement). I'm going to close this one as really old, feel free to re-open it if you still have problems or open new one in [new repo issue tracker](https://github.com/jenkinsci/ec2-fleet-plugin/issues)
