### ISSUE TITLE
Is the plugin deprecated?

### ISSUE THREAD

**Issue by Dmitry1987** [awslabs/ec2-spot-jenkins-plugin#19]
I wonder if the plugin does not work well, because I get these after a normal setup:

```
Aug 09, 2019 2:17:37 PM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@5809cd8 failed
com.amazonaws.services.ec2.model.AmazonEC2Exception: Fleet Request: sfr-66fce1c4-0ca3-4513-90d5-c09d4f283d66 is not a modifiable fleet request type. (Service: AmazonEC2; Status Code: 400; Error Code: FleetNotInModifiableState; Request ID: a5a9d6f7-ec01-4c6e-afca-ee9e0d85e2de)
```

It both doesn't scale up instances, and doesn't behave well overall. Seems like the plugin is abandoned by the official AWS support in this repo?

**Comment by terma** [comment]
Hi, it's not deprecated and we still support it, in fact, did a lot of nice things, however, this repo is old, according to Jenkins rule, all plugins should be under their organization, plugin place https://github.com/jenkinsci/ec2-fleet-plugin

**Comment by terma** [comment]
Will replay in https://github.com/jenkinsci/ec2-fleet-plugin/issues/131
